name       : font-symbola-ttf
version    : '9.0'
release    : 2
source     :
    - http://users.teilar.gr/~g1951d/Symbola.zip : 856de5857be48b8e31fc078fb93a9f3bd706b2552ba57b42863622f837cd3f35
license    : Public-Domain
component  : desktop.font
summary    : Symbol blocks of the Unicode Standard
description: |
    Symbol blocks of the Unicode Standard
install    : |
    install -m 0755 -d -D ${installdir}/usr/share/fonts/truetype/symbola
    install -m 0644 -D *.ttf ${installdir}/usr/share/fonts/truetype/symbola/.
