name       : font-symbola-ttf
version    : 8.0
release    : 1
source     :
    - http://users.teilar.gr/~g1951d/Symbola.zip : 0d568882ca4f38a8e7d487367c75f4d8d7cb9f902b9675b7f6620c139014dad1
license    : Public-Domain
summary    : Symbol blocks of the Unicode Standard
description: |
    Symbol blocks of the Unicode Standard
install    : |
    install -m 0755 -d -D ${installdir}/usr/share/fonts/truetype/symbola
    install -m 0644 -D *.ttf ${installdir}/usr/share/fonts/truetype/symbola/.
