name       : font-symbola-ttf
version    : '10.03'
release    : 4
source     :
    - http://users.teilar.gr/~g1951d/Symbola.zip : e7a77717aa25b83c8526c6653af5f468387d8763588a9510d4fa030a78d7b434
license    : Public-Domain
component  : desktop.font
summary    : Symbol blocks of the Unicode Standard
description: |
    Symbol blocks of the Unicode Standard
install    : |
    install -Dm0644 Symbola_hint.ttf ${installdir}/usr/share/fonts/truetype/symbola/Symbola.ttf
